### ISSUE TITLE
Usage with images from public folder

### ISSUE THREAD

**Issue by niksmac** [RafidMuhymin/astro-imagetools#1]
Is it possible to use this plugin for images from `/public` folder? 

Is this connected to RafidMuhymin/astro-image-demo/issues/1 ?

**Comment by thagxt** [comment]
From what I've read all the files in the `/public` folder aren't processed by Astro just copied as they are. So I suppose it's not possible.

> If you put a file into the `public`folder, it will not be processed by Astro. Instead it will be copied into the build folder untouched. This can be useful for assets like images and fonts, or when you need to include a specific file

from [Astro docs](https://docs.astro.build/en/core-concepts/project-structure/#public)

**Comment by niksmac** [comment]
Got it and makes sense. 
I think some documentation will help people to start trying this out.

**Comment by thagxt** [comment]
Yes, I agree 100%. 
btw Astro said they're going to implement something similar to this in the future...

**Comment by RafidMuhymin** [comment]
@niksmac and @thagxt `astro-imagetools` will work with images stored inside the `/public` folder. Because it's not something built into Astro. So, it works differently. But there's a high chance that it may change in the future. And yeah, we need a good documentation very quickly!

**Comment by thagxt** [comment]
It should but it doesn't or at least it never worked for me... 😞

**Comment by niksmac** [comment]
I don't think putting images inside `/src` since it is creating a static site out of it. We just need to get rid of that restriction from out head :D

**Comment by IanVS** [comment]
It looks like it's necessary to add the `/public` path explicitly to the `src`.  I think this is unfortunate, maybe this package could try looking inside `/public` automatically if it can't find the file at the provided src?  I'm trying to convert an `<img>` to `<Picture/>`, and it's unfortunate that the normal `src` can't be used.
