### ISSUE TITLE
Html code validity

### ISSUE THREAD

**Issue by seb-celinedesign** [RafidMuhymin/astro-imagetools#10]
The component always generates `<source>` tag with `width` and `height` attributes.
The spec have a simple mention for those attributes : 
https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element
MDN do not mention those : 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Source
And W3C validator cry at it : 
> Error: Attribute width not allowed on element [source](https://html.spec.whatwg.org/multipage/#the-source-element) at this point.
> Error: Attribute height not allowed on element [source](https://html.spec.whatwg.org/multipage/#the-source-element) at this point.

Browser take the ratio from the `<img>` width and height attributes, so i, personally, don't understand what width and height means on a `<source>` tag.

**Comment by RafidMuhymin** [comment]
Browsers don't always take the width and height from the attributes of the `<img>` element. For example, when you are using art directions, all the generated sources under the same `<picture>` element won't have the same width and height. In those cases, adding the `width` and `height` attributes to the `<source>` elements are necessary.

**Comment by seb-celinedesign** [comment]
> Browsers don't always take the width and height from the attributes of the `<img>` element. For example, when you are using art directions, all the generated sources under the same `<picture>` element won't have the same width and height. In those cases, adding the `width` and `height` attributes to the `<source>` elements are necessary.

😉👍
