### ISSUE TITLE
Astro JS and remote image url (headless CMS) does not package/bundle on build

### ISSUE THREAD

**Issue by Bacp** [RafidMuhymin/astro-imagetools#114]
"astro-imagetools": "^0.6.10"
 "astro": "^1.0.6"

Pretty clean install from a few days back, got everything wired up and after build is shows in de CLI is optimized the images.
After I check the dist folder it seems the images are not copied to the assets folder.
The compiled HTML contains the accurate code and paths to the dist/assets folder but the images are missing.

For example:
`
<BackgroundImage 
	src={image}
	format={["webp", "jpg"]}
	breakpoints={[400, 640, 800, 1024, 1280]}>
`

The image is just a remote URL, which works fine while running dev. 

Maybe I'm missing something? Seems more related to a bundler.

**Comment by AndreaPontrandolfo** [comment]
duplicate of #111

**Comment by Bacp** [comment]
My bad, duplicate
