### ISSUE TITLE
Use with @astrojs/renderer-solid

### ISSUE THREAD

**Issue by millette** [RafidMuhymin/astro-imagetools#12]
Looks like it works with react, vue and svelte, but not solidjs.

**Comment by RafidMuhymin** [comment]
@millette Can you share what are you doing? I tried in my machine and I see I can't even use `solid-js`.

**Comment by millette** [comment]
I have in astro.config.js:

```js
export default ({
  renderers: ['@astrojs/renderer-solid']
})
```

And in package.json:

```json
{
  "dependencies": {
    "@astrojs/renderer-solid": "^0.4.0"
  }
}
```

My project is currently private, sorry. However, there's an official example <https://github.com/withastro/astro/tree/main/examples/framework-solid>.

**Comment by RafidMuhymin** [comment]
Is the `framework-solid` example working locally if you don't use `astro-imagetools`?

**Comment by millette** [comment]
Works for me.

```sh
mkdir astro-framework-solid
cd astro-framework-solid
npm init astro -- --template framework-solid
npm i
npm run dev # launch browser on localhost:3000 - it works
npm run build
npm run preview # launch browser on localhost:3000 - it works too
```

**Comment by RafidMuhymin** [comment]
NVM, I was using an older version of the renderer. Now after upgrading everything is working fine. The Solid components are rendering images fine too. Exactly what issue are you facing? And does this go away if you upgrade the `@astrojs/renderer-solid` package?

**Comment by millette** [comment]
Can you share your example (based on framework-solid)?

I'll revisit the project later this week and get back to you asap.

**Comment by RafidMuhymin** [comment]
I'm sharing a GitPod link with everything set up https://rafidmuhymin-astroimaged-4puvj7bf1ph.ws-us34.gitpod.io/

**Comment by millette** [comment]
> operation not permitted: missing create permission on workspaceInstance

I never used gitpod - I created an account thru github.

**Comment by RafidMuhymin** [comment]
Sorry for issue @millette! I'm not very familiar with GitPod too. I used it because it will provide a complete workspace for testing. However, here's a CodeSandbox link https://codesandbox.io/s/tender-firefly-wkn3kv?file=/src/pages/index.astro

**Comment by RafidMuhymin** [comment]
I'm closing this issue @millette and @KyleFontenot. Feel free to reopen this issue or create another issue if you face any problem.
