### ISSUE TITLE
style prop

### ISSUE THREAD

**Issue by KyleFontenot** [RafidMuhymin/astro-imagetools#13]
Any plans for adding in a `style` prop? 
I got it working in a fork. 

Passing style through to `getBackgroundStyles` works well to style the actual image instead of the `<picture>` tag.

**Comment by RafidMuhymin** [comment]
Yeah, there are definitely plans to support all the HTML attributes for the component. The `style` will be one of them. But I think you are talking about pushing styles to the `<style>` tag. I am interested to see what you are doing.

**Comment by djmtype** [comment]
I've found that any styles defined within the component's `<style>` are being ignored when it comes to the `<img>`.  Is that currently the case?

**Comment by KyleFontenot** [comment]
That's correct. But that's because of how Astro scopes the `<style>` tag. 

https://docs.astro.build/en/guides/styling/

~> Section "Styling Children". Using `:global(img)` should work.

**Comment by RafidMuhymin** [comment]
@KyleFontenot this feature is now supported since `0.6.0`. You can now set custom styles by passing `attributes={{ style: "width 100%" }}` to any of the supported components or you can set a custom class name in the same way. Feel free to reopen the issue if you are facing any issues.
