### ISSUE TITLE
Config options missing in docs

### ISSUE THREAD

**Issue by silveltman** [RafidMuhymin/astro-imagetools#148]
The docs seem to be incomplete, no config options.
![image](https://user-images.githubusercontent.com/52583398/210429975-c3027998-069a-41b2-ad22-5ad99f4e667b.png)

This is the case for all components and API's

**Comment by Danny-Rodriguez** [comment]
Same here. I imagine it's related to yesterday's update.

**Comment by Felix-Icaza** [comment]
This snapshot may help: [https://web.archive.org/web/20221127093425/https://astro-imagetools-docs.vercel.app/en/introduction](https://web.archive.org/web/20221127093425/https://astro-imagetools-docs.vercel.app/en/introduction)

**Comment by RafidMuhymin** [comment]
Thanks for reporting the issue @silveltman . Closing this since the issue has been resolved.
