### ISSUE TITLE
404 images for Astro@v2

### ISSUE THREAD

**Issue by ixam1** [RafidMuhymin/astro-imagetools#153]
I wanted to try out Astro v2 with this package and it seems like the asset urls that are created are falsy. All images are 404, this is the error message:
```
18:06:19 [serve]    404 /assets/[object Object]@3648w.6f826ced.jpeg
18:06:19 [serve]    404 /assets/[object Object]@206w.dfd2c3da.png
18:06:19 [serve]    404 /assets/[object Object]@640w.aad2af86.jpeg
```

**Comment by ixam1** [comment]
I created a PR to fix this https://github.com/RafidMuhymin/astro-imagetools/pull/154

**Comment by RafidMuhymin** [comment]
Thanks for opening the issue. Closing this since #154 has been merged.
