### ISSUE TITLE
Check for `isSsrBuild` is incorrect

### ISSUE THREAD

**Issue by johnzanussi** [RafidMuhymin/astro-imagetools#157]
When using `@astro/vercel` adapter with the `static` target this plugin incorrectly sets `isSsrBuild` to true which causes the build to fail.

https://docs.astro.build/en/guides/integrations-guide/vercel/#targets

```js
// astro.config.mjs
import vercel from '@astrojs/vercel/static';

export default defineConfig({
    ...
    output: 'static',
    adapter: vercel(),
    ...
});
```

[astro-imagetools/integration/index.js](https://github.com/RafidMuhymin/astro-imagetools/blob/main/packages/astro-imagetools/integration/index.js#L18)
```js
// astro-imagetools/integration/index.js
export default {
  name: "astro-imagetools",
  hooks: {
    "astro:config:setup": async function ({ config, command, updateConfig }) {
      const environment = command;

      const isSsrBuild = command === "build" && !!config.adapter;
      ...
```
It seems as if an additional check for `config.output === 'server'` is necessary to support Vercel's `static` output target.

I'm happy to open a PR to fix this issue if ya'll are accepting them.

**Comment by johnzanussi** [comment]
I created a PR for the fix. #158

**Comment by RafidMuhymin** [comment]
Thanks for opening the issue. Closing this since #158 has been merged.
