### ISSUE TITLE
Build mode not working 

### ISSUE THREAD

**Issue by KyleFontenot** [RafidMuhymin/astro-imagetools#16]
Build mode is erroring out for me.

The Image import alone throws the error: `import Image from "astro-imagetools";` with or without including it in the component. I've updated to all latest node packages, cleared the cache, and tested experimental flags but no cigar. The Image component works beautifully in dev. Have no idea how to troubleshoot.

Error:
```
'createHash' is not exported by __vite-browser-external, imported by node_modules/imagetools-core/dist/index.mjs
file: /home/kyle/Software/CarbideSawTool/node_modules/imagetools-core/dist/index.mjs:2:9
1: import sharp from 'sharp';
2: import { createHash } from 'crypto';
            ^
3: 
4: const METADATA = Symbol('image metadata');
Error: 'createHash' is not exported by __vite-browser-external, imported by node_modules/imagetools-core/dist/index.mjs
    at error (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:12477:16)
    at Module.traceVariable (/home/kyle/Software/CarbideSawTool/node_modules/rollup/dist/shared/rollup.js:12835:29)
```

**Comment by RafidMuhymin** [comment]
@KyleFontenot Can you share a link to the code? And are you able to reproduce this issue with the demo project https://github.com/RafidMuhymin/astro-image-demo ?

**Comment by KyleFontenot** [comment]
I couldn't recreate it actually. Once I cloned it, the clone worked just fine. 
Maybe it had to do with updating the package with a previous cache. I don't know.
