### ISSUE TITLE
Feature: Add class name option

### ISSUE THREAD

**Issue by djmtype** [RafidMuhymin/astro-imagetools#18]
This plugin is awesome! I didn't see the ability to add a class name. Please consider this as a prop.

**Comment by RafidMuhymin** [comment]
@djmtype this feature is now supported. You can now set custom class names by passing `attributes={{ class: "custom-class" }}` to any of the supported components.

**Comment by rwwagner90** [comment]
@RafidMuhymin Am I doing something wrong here?

```astro
          <Img
            attributes={{
              class: 'h-[50px] w-auto',
            }}
            height={100}
            format="webp"
            src="/img/logo.png"
            width={100}
          />
```

It does not add the class, and I get: `Object literal may only specify known properties, and 'class' does not exist in type 'Omit<Attributes, "picture" | "container">'`

**Comment by rwwagner90** [comment]
For anyone that lands here, it has to be nested:

```
  attributes={{
          img: {
            class: 'h-auto max-w-xl mt-8 mx-auto w-full lg:ml-0 lg:mt-0'
          }
        }}
```
