### ISSUE TITLE
markdown integration 

### ISSUE THREAD

**Issue by mash-graz** [RafidMuhymin/astro-imagetools#20]
is it already possible to process and optimize images in markdown files by just utilizing query-encoded-filename-suffixes but otherwise common markdown image-embedding-syntax by this tool in astro? this would be very helpful to reuse existing markdown content and editing tools without much modifications.

**Comment by RafidMuhymin** [comment]
@mash-graz The `astro-imagetools` package yet doesn't have any specific image tool for processing markdown files. But as Astro supports importing components inside the Markdown Frontmatter, you can import the `<Image />` component and use it your MD files until a built-in solution becomes available.

**Comment by RafidMuhymin** [comment]
@mash-graz `astro-imagetools` now automatically generate image sets for markdown images. For more info, check https://www.npmjs.com/package/astro-imagetools#markdown-images. I am closing this issue for now. Feel free to reopen this issue if need and don't forget to share your thoughts!

**Comment by mash-graz** [comment]
**thanks!**  -- that's a really nice improvement!

btw.: does this solution also accept URL-query-encoded options?

because that seems to be the only way to control the image processing in a pure markdown specific manner, and the examples in the documentation don't illustrate this kind of utilization...

well -- i'll try to find it out myself... ;)

but **thanks** again!

**Comment by RafidMuhymin** [comment]
Thanks, @mash-graz for the feedback and yes, it's completely fine to pass config options using query parameters. Thanks for the feedback, I will try to update the doc as soon as possible.

**Comment by kissu** [comment]
May I suggest an opt-out of the markdown images? Got an issue because it was building it for me without me noticing and I was kinda surprised that we cannot disable this behavior.

Thanks for the amazing library btw! 🙏🏻
