### ISSUE TITLE
Inline style on image creates excess gap

### ISSUE THREAD

**Issue by djmtype** [RafidMuhymin/astro-imagetools#22]
By default, this plugin adds an inline style, `display:inline-block`, to the `img` element. However, this creates a visual space at the bottom of the image because it's  placed within another container – the `picture` element. 

I'm unsure how this should be handled. Adding `vertical-align: middle` would fix this, but then this would have to be a global style because of how Astro scopes the `<style>` tag. Besides, we probably don't want *all* images to be vertically aligned this way when it comes to different contexts. 

Adding `display:block` would also fix this. However, same problem as I mentioned earlier. Perhaps, let the developer decide, and don't add `display: inline-block` as an inline style?

![Screen Shot 2022-03-20 at 6 13 27 PM](https://user-images.githubusercontent.com/930713/159188431-a082354b-f1a1-4b72-8069-ed59a9f851e6.png)

**Comment by IanVS** [comment]
As far as I can tell, vertical-align: middle does not actually change the positioning of the image, but rather collapses the extra inline space normally provided for descenders.  I have a PR open that should fix this issue.
