### ISSUE TITLE
global configuration of the component

### ISSUE THREAD

**Issue by gtnbssn** [RafidMuhymin/astro-imagetools#23]
Is there a way to set some options globally?

Reading the documentation it seems i would have to set the breakpoints and desired image formats every time i use the component. Maybe i am missing something?

**Comment by RafidMuhymin** [comment]
@gtnbssn Hi :wave: @gtnbssn. Yes, there's a way to define global configs for the component. You can define the configs by defining an `image` object in the Astro config.

**Comment by gtnbssn** [comment]
Aaah makes sense, i will follow the next versions! Thanks a lot!!

I was thinking otherwise i could probably just create my own component that extend yours and has my default props set.

This component is definitely selling me on Astro by the way, great job!!

**Comment by RafidMuhymin** [comment]
Thank you @gtnbssn! And another good news, `astro-imagetools@0.4.0` was released two days ago which supports global config options. Check https://www.npmjs.com/package/astro-imagetools#global-config-options for more information. I am closing the issue now. Feel free to reopen the issue if necessary.
