### ISSUE TITLE
Feature (very low priority): CSS for placeholder 

### ISSUE THREAD

**Issue by KyleFontenot** [RafidMuhymin/astro-imagetools#24]
Haven't investigated the code, but would it be possible to adjust the CSS of the transitions of the placeholders? I just fiddled with the `tracedSVG` placeholder (which is great), and I thought of the opportunity to be able to apply a `filter:` for recoloring the black and white.

Noticed a long time ago that Gatsby's Image tracedSVG placeholder was black and white as well, so was curious if there is a major limitation with this.

**Comment by RafidMuhymin** [comment]
JS animations are used for the transitions of the placeholder. If you check the `onload` attribute of the generated `<Img>` element, you'll be able to see what is being done.

**Comment by RafidMuhymin** [comment]
And thanks for proposing this feature, I will try to work on this.

**Comment by RafidMuhymin** [comment]
@KyleFontenot since `0.6.0`, it's setting custom class names and inline styles is supported via the `attributes` prop. Check https://astro-imagetools-docs.vercel.app/en/components/Picture#attributes for more information.
