### ISSUE TITLE
overly verbose logging

### ISSUE THREAD

**Issue by mash-graz** [RafidMuhymin/astro-imagetools#25]
could you please reduce the unnecessary verbose logging generated by: 

https://github.com/RafidMuhymin/astro-imagetools/blob/422fcb7a6545b5fe2fe45df7c4f15812c459aeea/src/component/utils/renderImage.js#L52

or make it an optional feature behind a 'debug/benchmark' flag.

unfortunately this is not only a cosmetic issue, but a behavior, which can be very annoying, if you want/need to utilize simple logging yourself in the development process but the relevant output becomes nearly invisible and always needs manual back scrolling on the terminal because of all this `"Image at ... optimized in ... ms"` lines.

**Comment by RafidMuhymin** [comment]
Thanks, @mash-graz. Yeah, it's true that the logging is verbose and it's triggered on every reload. And it's already on my to-do list to improve the logging. So, I hope the package will soon receive an update for this.

**Comment by RafidMuhymin** [comment]
@mash-graz Closing this issue as the logging messages have been updated and the components and APIs no longer log messages on every reload. Any opinion will be appreciated.
