### ISSUE TITLE
Build Error using <Image> component : "TypeError: Cannot destructure property 'getImageDetails'..."

### ISSUE THREAD

**Issue by florian-s-code** [RafidMuhymin/astro-imagetools#26]
Hi, thanks for this cool plugin.
I want to report this bug that blocks my site build.

Astro-imagetools : 0.3.1
Astro : 0.25.2
Node : v17.8.0

Here is the build command output:
```console
❯ npm run build

> protfolio@0.0.1 build
> astro build

13:35:00 [config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
13:35:00 [build] Initial setup...
13:35:00 [build] Collecting page data...
13:35:02 [build] Completed in 2.72s
13:35:02 [build] Discovering entrypoints...

 building resources 

vite v2.8.6 building for production...
✓ 22 modules transformed.
dist/entry.ef0858d2.js   128.75 KiB / gzip: 41.47 KiB
Completed in 0.77s

13:35:03 [build] Building for SSR...
13:35:09 [build] Completed in 5.46s

 generating static routes 

TypeError: Cannot destructure property 'getImageDetails' of '(intermediate value)' as it is undefined.
    at file:///home/xxx/Documents/dev/new-site/dist/entry.mjs?time=1648380909120:3271:26
```

I have tracked the error to this snippet :
https://github.com/RafidMuhymin/astro-imagetools/blob/ffe6f1afe2d70b01088121d8ff7497dced7551fe/src/component/utils/getProcessedImage.js#L26-L29

Any idea what could be the problem ?

**Comment by mash-graz** [comment]
i'm also fighting this issue.

it's only affecting the the `build` stage but not the live `dev` server.

perhaps its caused by an astro issue, but it doesn't affect other similar plugins (e.g. `astro-icon`).

as a temporary workaround  i have to use `astro 24.3`

**Comment by RafidMuhymin** [comment]
@mash-graz It's a bug introduced in `astro@0.25`. So, we'll have to wait until it gets fixed in `astro`.

**Comment by mash-graz** [comment]
i can't reproduce the error anymore with astro  0.25.4 and astro-imagetools 0.4.1.

it seems to work again! -- but i have no idea, what really happened resp. caused this troubles -- which also isn't a very satisfaying feeling...

**Comment by florian-s-code** [comment]
@mash-graz This was discussed briefly on Discord.
The way the entry.mjs file was generated (during the Astro build process) put the astro-magetools code too early in the file which was causing this problem.
It was fixed in the subsequent version by the Astro team.
Thanks RafidMuhymin for investigating.
