### ISSUE TITLE
Request: Fallback for Disabled JS

### ISSUE THREAD

**Issue by SlicedSilver** [RafidMuhymin/astro-imagetools#28]
### Issue
Currently if the user has disabled JS then the placeholder blurred image will remain stacked on top of the actual image even after it has finished loading. Thus the image remains blurry.

### Reason
The component is using the `onload` event to hide the placeholder, however this won't run if the user has disabled JS.
https://github.com/RafidMuhymin/astro-imagetools/blob/e38ff11bf1a241a3c05367f402d628f50282c79c/utils/getImg.js#L36-L43

### Possible Solution
A possible solution would be:
* Have the initial styling state be that the placeholder is hidden (or stacked below the image). Either by setting the z-index or opacity values, i.e. `opacity: 0;`.
* Then use the `onloadstart` event to set the styles required to show the placeholder (as it currently is). i.e. `opacity: 1;`.
* The existing `onload` event shouldn't need changing.

That should work for users with disabled JS but still provide the current fade in effect for everyone else.

I would suspect that the preferred approach might be to use `z-index` over `opacity` because then the image will load on top of the blurred placeholder, thus the placeholder still serves some purpose.

Thanks for awesome project by the way 😄

**Comment by RafidMuhymin** [comment]
Hats off to you @SlicedSilver !

**Comment by RafidMuhymin** [comment]
@SlicedSilver this issue has been fixed in the `astro-imagetools@0.5.6` release. Thank you again for reporting this issue. And I was able to fix the issue without even using a `<script>` tag or the `loadstart` event.

**Comment by SlicedSilver** [comment]
Working for me 👍

Thanks for update, really appreciate the great work you've done with this project.

**Comment by RafidMuhymin** [comment]
Thank you!
