### ISSUE TITLE
No more listet in https://astro.build/integrations/

### ISSUE THREAD

**Issue by philschonholzer** [RafidMuhymin/astro-imagetools#29]
A few days ago I found this integration over the https://astro.build/integrations/ page, but now this project is no more listet. Is there a reason for that? Should this project not be used/discovered?

<img width="747" alt="Screenshot 2022-04-08 at 13 07 38" src="https://user-images.githubusercontent.com/7238141/162424135-77b8087c-9234-49b3-99c5-655d922a5452.png">

**Comment by RafidMuhymin** [comment]
Thank you for reporting this @philschonholzer. Yeah, I'm also seeing that it's no longer listed. I will report it to the core team. Thank you again.
