### ISSUE TITLE
Image height="NaN"

### ISSUE THREAD

**Issue by bronze** [RafidMuhymin/astro-imagetools#31]
My html is writing my images with a `height=NaN` anyone seen this?

my code:
`<Image src="/src/ales-nesetril-Im7lZjxeLhg-unsplash.jpg" alt="" placeholder="none" fadeInTransition="false" formats="avif,webp,jpg" breakpoints={[300, 600, 900, 1200, 1500]} objectFit="cover" layout="fill" />`

html excerpt:
```
<source
  srcset="/assets/asset.617d1828.avif 300w, /assets/asset.7ab93e77.avif 600w, /assets/asset.9b2b83ec.avif 900w, /assets/asset.48a66d87.avif 1200w, /assets/asset.e0f0869a.avif 1500w"
  sizes="(min-width: 1500px) 1500px, 100vw"
  width="1500"
  height="NaN"
  type="image/avif"
/>
```

**Comment by RafidMuhymin** [comment]
@bronze I am not getting this issue with the code you provided. If it was present it may have been fixed in the recent upgrade.

**Comment by RafidMuhymin** [comment]
And you are using the `fadeInTransition` incorrectly, it should be `fadeInTransition={false}`. And there's no supported prop named `formats`. If you wanted to use `format`, it should be `format={["avif", "webp", "jpg"]}`
