### ISSUE TITLE
.base option is not honored

### ISSUE THREAD

**Issue by bbbenji** [RafidMuhymin/astro-imagetools#39]
The output of `yarn build` results in the assets generated by astro-imagetools to be loaded from `/assets/` instead of the defined base option, eg: `/foo/assets/`. Astro@1.0.0-beta.17

``` astro.config.mjs
import { defineConfig } from 'astro/config';
import astroImagePlugin from 'astro-imagetools/plugin';

export default defineConfig({
  vite: {
    plugins: [astroImagePlugin],
  },
  site: 'https://example.com',
  base: '/foo',
});

```

**Comment by RafidMuhymin** [comment]
@bbbenji can you check if the `base` config works with the latest version of `astro-imagetools`?
