### ISSUE TITLE
Astro builds timing out then getting killed

### ISSUE THREAD

**Issue by MrTeapot** [RafidMuhymin/astro-imagetools#40]
Hey!

This plugin is a critical missing piece in the Astro ecosystem. Keep up the good work!

I installed this plugin and quickly got it running in my development environment. The only trouble I had was that I got status 500 errors when visiting markdown generated pages that had svg images, which I had exported from Figma. I solved it by converting the svgs to pngs. The development server can also be a little bit slow when visiting different pages, sometimes a couple of minutes to load.

I did however, get problems running "astro build".
It got really slow, the "Collecting build information..." step takes several minutes. Running on my rather powerful PC. 
After it's done with that step, it continues to the "generating static routes" step. I can see in the console that it has generated multiple responsive images along with the markdown files that was referencing them. And I get a "Completed in X ms" after a while. Then my PC fans go Brrrr for several minutes.  

After that, i simply get a "Killed" in the console. No more information is provided.

I tried pushing my changes to github, and let my Github actions build server try to build. The CPU went to 100% and the build process died after 25 minutes. I was forced to restart my server as it became unresponsive.

My site has around 15 images in total, the largest being around 4mb.
I have recently converted the site from Gatsby to Astro, and Gatsby image tools had no issues doing similiar image processing on my images.

I'm sorry that I'm unable to provide more detailed information about my issue. Let me know how I can help you debug the issue.

- astro 1.0.0-beta.17
- astro-imagetools 0.5.8
- Running in WSL2/Ubuntu

Thanks in advance.

**Comment by skourismanolis** [comment]
I've run into similar problems during building #41 My current workaround is to use version 0.5.3

**Comment by RafidMuhymin** [comment]
@MrTeapot are you able to build successfully if you use `v0.5.3` like suggested by @skourismanolis ??

**Comment by MrTeapot** [comment]
> @MrTeapot are you able to build successfully if you use `v0.5.3` like suggested by @skourismanolis ??
Nope! I changed the version in my package.json to 0.5.3, did rm -rf node_modules, then npm i.
Still the same issue. I'm also getting issues with the dev environment now. Tried 0.5.8 again and now both dev and build is super slow.

**Comment by skourismanolis** [comment]
I simply did a `yarn install astro-imagetools@0.5.3` I haven't tried clean installation like you did

**Comment by tusamni** [comment]
Same issue here. Timed out builds, dev seems fine.

**Comment by RafidMuhymin** [comment]
@tusamni do you notice improved performance if you downgrade to `v0.5.3` ??

**Comment by tusamni** [comment]
Doesn't seem like it. Here's my build from `0.5.3`

![Screenshot_5](https://user-images.githubusercontent.com/9271145/165637359-afd8d48a-9aa4-4121-af3b-1b6d584130ac.png)

**Comment by RafidMuhymin** [comment]
@tusamni a fix for this has been released in `astro-imagetools@0.6.7`. Closing this issue for now. Feel free to reopen the issue if you are facing any performance issues. And can you share if the build is faster than before now?
