### ISSUE TITLE
Picture component does not accept empty "alt" property

### ISSUE THREAD

**Issue by fabianmakila** [RafidMuhymin/astro-imagetools#42]
## Issue description
I'm using a Picture element like this
```html
<Picture
  src="/src/path-to-image"
  alt=""
/>
```
Which throws the following error
```
 error   The "alt" property is required by Picture
    at /node_modules/astro-imagetools/utils/filterConfigs.js:20:13
    at Array.forEach (<anonymous>)
    at Module.filterConfigs [as default] (/node_modules/astro-imagetools/utils/filterConfigs.js:18:19)
    at Module.getFilteredProps [as default] (/node_modules/astro-imagetools/utils/getFilteredProps.js:76:43)
    at Module.renderPicture [as default] (/node_modules/astro-imagetools/api/renderPicture.js:12:63)
    at /Users/fabian/test/node_modules/astro-imagetools/components/Picture.astro:5:0
    at renderToString (/node_modules/astro/dist/runtime/server/index.js:342:27)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:125:26)
```

This does not happen if the "alt" property has text.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-alt) setting the alt text to "" should be completely acceptable behavior:

> Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it's decoration or a tracking pixel), and that non-visual browsers may omit it from [rendering](https://developer.mozilla.org/en-US/docs/Glossary/Rendering_engine). Visual browsers will also hide the broken image icon if the alt is empty and the image failed to display.

## Technical details
Astro version: `1.0.0-beta.17`
Astro imagetools version: `0.5.8`
Node version: `17.2.0`
Operating System: `macOS Monterey 12.3`

**Comment by RafidMuhymin** [comment]
Hmm... It's an accepted behavior?! It's interesting! Thank you for informing me @fabianmakila ! I intentionally didn't allow this but as it's acceptable behavior, I will push a fix to allow this. Thank you again.

**Comment by IanVS** [comment]
Hi, this is fixed by https://github.com/RafidMuhymin/astro-imagetools/pull/72.

**Comment by RafidMuhymin** [comment]
Closing this issue now @fabianmakila. Feel free to open another issue if you are facing any issues.
