### ISSUE TITLE
Image without artDirectives attribute doesn't generate the picture tag

### ISSUE THREAD

**Issue by seb-celinedesign** [RafidMuhymin/astro-imagetools#5]
Following astro code : 
`<Image
        src="..."
        alt="..."
        width={320}
      format={['avif', 'webp']}
        breakpoints={[320, 640]}
      />`
doesn't generate a `<picture>` tag, only `<source>` and `<img>` tags.

**Comment by RafidMuhymin** [comment]
@seb-celinedesign The issue has been fixed in `v0.0.16`. Can you confirm it?

**Comment by seb-celinedesign** [comment]
> @seb-celinedesign The issue has been fixed in `v0.0.16`. Can you confirm it?

Yes it is !
