### ISSUE TITLE
Allow global breakpoints for markdown images

### ISSUE THREAD

**Issue by IanVS** [RafidMuhymin/astro-imagetools#53]
I don't see any way in the docs to specify a set of breakpoints to use for simple markdown images.  Is it possible?  I tried adding an `astro-imagetools.config.mjs` like this:

```js
import { defineConfig } from "astro-imagetools/config";

export default defineConfig({
  breakpoints: [576, 768, 992, 1200],
});

```

But it seemed to have no effect.

**Comment by ixartz** [comment]
I got exactly the same issue by defining a breakpoints and it seems there is no effect.

I have also tried other configuration variable and it was working in the past. But not now. Is it because I have updated Astro to the latest version?
