### ISSUE TITLE
Allow disabling markdown image processing

### ISSUE THREAD

**Issue by IanVS** [RafidMuhymin/astro-imagetools#57]
Until there's a way to configure breakpoints for markdown images (https://github.com/RafidMuhymin/astro-imagetools/issues/53), I'd like to disable processing them at all.  I only have two images in a single markdown file, but if I remove those images, my build time goes from 67s to 20s, so they're taking a ton of time to process.  I'd like to just use the files without processing them, for now.  Maybe there can be a global config option to disable them?

**Comment by RafidMuhymin** [comment]
@IanVS are you still facing this issue after the recent changes and fixes?

**Comment by IanVS** [comment]
I'm trying to debug the bad performance with markdown processing, but making progress.  If I can take care of that, I think this feature would not be needed.

**Comment by RafidMuhymin** [comment]
As #75 has been merged, can we close this issue now @IanVS ?
