### ISSUE TITLE
Docs example shows `includeSourceFormat` property, but that doesn't exist

### ISSUE THREAD

**Issue by mvolfik** [RafidMuhymin/astro-imagetools#59]
The first example in https://astro-imagetools-docs.vercel.app/en/components/Img#formatoptions

**Comment by RafidMuhymin** [comment]
Thanks for reporting the issue @mvolfik ! The `<Img />` component documentation has been updated https://astro-imagetools-docs.vercel.app/en/components/Img#formatoptions.
