### ISSUE TITLE
Missing astroViteConfigs.js reported with latest v0.6.4

### ISSUE THREAD

**Issue by AirBorne04** [RafidMuhymin/astro-imagetools#63]
Hi,

thank you for this plugin it is really needed!

I have encountered `error ENOENT: no such file or directory, open '...../astroViteConfigs.js'` when running the latest v0.6.4 with astro `1.0.0-beta.27`. I have used a plain installation with `react` and `tailwind`integrations. and my config looks like this:
```
import { defineConfig } from 'astro/config';
import react from "@astrojs/react";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";

import { astroImageTools } from "astro-imagetools";

// https://astro.build/config
export default defineConfig({
  integrations: [react(), tailwind(), sitemap(), astroImageTools],
  experimental: {
    integrations: true
  }
});
```

when rolling back to v0.6.3 this error is not reported.

**Comment by AirBorne04** [comment]
I need to mention that I am running on windows and the `import { posix as path } from "path";` does create a problem when using the `path.resolve` together with the `fileURLToPath(import.meta.url)` on a windows machine.

**Comment by IanVS** [comment]
This is fixed by https://github.com/RafidMuhymin/astro-imagetools/pull/62, but is not yet released.

**Comment by AirBorne04** [comment]
Hey,
i also had to fix the coding on the `integrations/index.js` to make it work. Here it finds the file, but messes up the path config for the project (creating compile errors e.g. not locating the image files), so i switched to `import { posix as path, resolve } from "path"` as well. With the same adjustments for locating the config file.
