### ISSUE TITLE
Crash if no astro-imagetools.config file provided

### ISSUE THREAD

**Issue by SlicedSilver** [RafidMuhymin/astro-imagetools#74]
I'm unable to start astro (run or build) since updating to v0.6.5 of this plugin. 

Here is the error output from the terminal:
```
.../node_modules/astro-imagetools/utils/runtimeChecks.js:46
const rawGlobalConfigOptions = configFunction.default ?? {};
                                              ^

TypeError: Cannot read properties of null (reading 'default')
    at .../node_modules/astro-imagetools/utils/runtimeChecks.js:46:47
```

On my machine the error occurs on this line:
```js
const rawGlobalConfigOptions = configFunction.default ?? {};
```

The issue is resolved by adding the `?` after the `configFunction`, like this:
```js
const rawGlobalConfigOptions = configFunction?.default ?? {};
```
---
However I notice that the source code is **already correct** in this regard:
https://github.com/RafidMuhymin/astro-imagetools/blob/c79d0f2249835e8af31ce3b2fcba53763ef4b81c/packages/astro-imagetools/utils/runtimeChecks.js#L46

I've tried uninstalling and re-installing the npm package, and still get the same issue. 

Checking the package provided by npm via RunKit:
https://npm.runkit.com/astro-imagetools/utils/runtimeChecks.js?t=1653047907617
Still is the missing the optional chaining `?` character.

**Comment by IanVS** [comment]
Hi, this was fixed in https://github.com/RafidMuhymin/astro-imagetools/pull/71, and is awaiting a release.

**Comment by SlicedSilver** [comment]
Thanks @IanVS , I did notice the fix was already merged but wrongly assumed that the most recent release included the latest commits (and thus there was perhaps an issue with the building or publishing). 

I'll close this issue once the fix is released. 👍🏻 (in case someone else comes across the same issue)

**Comment by SlicedSilver** [comment]
@RafidMuhymin Thanks. The issue is fixed. 👍🏻
