### ISSUE TITLE
Unable to build with markdown images. Getting killed or segmentation fault

### ISSUE THREAD

**Issue by MrTeapot** [RafidMuhymin/astro-imagetools#78]
![image](https://user-images.githubusercontent.com/1011679/169603884-37dffad2-5af2-4615-9e67-d2c354fd99b8.png)
After reaching "Completed in.." my pc fans go Brrrr for a while, then the build gets killed or gets a segmentation fault.

Reproduced in this repo as a basic example: https://github.com/MrTeapot/astro-imagetools-build-killed-reproduction
Try cloning, "npm i", then "npm run build".

Running inside WSL2, Ubuntu 20.04 LTS.

CPU and memory usage becomes extremely high during the build.

**Comment by RafidMuhymin** [comment]
@MrTeapot confirming the issue. The build is getting killed and exits with error code `137`. That means the process ran out of memory. It's right that the images are large but I just tested and `astro-imagetools` is working fine with this `11.92MB` image https://wallpaperaccess.com/download/16k-resolution-82311. There may be some other issue.

**Comment by MrTeapot** [comment]
The ram usage is constantly increasing until it runs out of memory.
![image](https://user-images.githubusercontent.com/1011679/169649717-aea2dea8-754c-452c-a953-9a532b5ccfc5.png)

Looks like 15gb is available in WSL2, although I have 32gb installed. But 15 should be more than enough.

I've tried running this in node 14.17.1 and 18.2.0 with no difference.

**Comment by RafidMuhymin** [comment]
@MrTeapot a fix for the performance regression has been merged and released in `0.6.9`. https://github.com/MrTeapot/astro-imagetools-build-killed-reproduction is now building fine after upgrading to `astro-imagetools@0.6.9`.

**Comment by MrTeapot** [comment]
My builds are working now when using 0.6.9.
